INCLUDE< device\m16def.f>
INCLUDE" delay.f"

PORTD CONSTANT BEEPER-PORT
DDRD  CONSTANT BEEPER-DDR
PIND  CONSTANT BEEPER-PIN
PD7   CONSTANT BEEPER-OUT

: BEEPER-ON  BEEPER-OUT BEEPER-PORT SET-BIT ; INLINE
: BEEPER-OFF BEEPER-OUT BEEPER-PORT CLR-BIT ; INLINE

: BEEPER-INIT BEEPER-OUT BEEPER-DDR SET-BIT BEEPER-OFF ; INLINE

: BEEP-MS BEEPER-ON DELAY-MS BEEPER-OFF ; INLINE

: BEEP-SEC BEEPER-ON DELAY-SEC BEEPER-OFF ; INLINE

: INIT-BEEPER BEEPER-INIT ; INIT
