INCLUDE< cinout.f>
INCLUDE" delay.f"
INCLUDE" i2cmaster.f"

PSTRING" DS1307 busy" msg_ds1307_busy

$D0 CONSTANT DS1307_A

: PUT-BUSY-MSG CLS msg_ds1307_busy PTYPE EXIT ;

: DS1307-TUNING
  DS1307_A I2C-WRITE-MODE + I2C-START NOT
  IF
    PUT-BUSY-MSG
  ELSE
    0 I2C-WRITE DROP I2C-STOP
    100 DELAY-MS
    DS1307_A I2C-READ-MODE + I2C-REP-START NOT
    IF
      PUT-BUSY-MSG
    ELSE
      I2C-READ-NACK I2C-STOP 100 DELAY-MS $7F AND
      DS1307_A I2C-WRITE-MODE + I2C-START NOT
      IF
        DROP PUT-BUSY-MSG
      ELSE
        0 I2C-WRITE DROP I2C-WRITE DROP I2C-STOP 100 DELAY-MS
        DS1307_A I2C-WRITE-MODE + I2C-START NOT
        IF
          PUT-BUSY-MSG
        ELSE
          $7 I2C-WRITE DROP $90 I2C-WRITE DROP I2C-STOP
        THEN
      THEN
    THEN
  THEN
;

: DS1307-INIT DS1307-TUNING ; INIT
