INCLUDE< cinout.f>
INCLUDE" lcd.f"

: INIT-LCD-INOUT
  ' LCD-EMIT       EMIT-WORD          D! 
  ' LCD-LINE-COL   GOTO-LINE-COL-WORD D!
  ' LCD-CURSOR-ON  CURSOR-ON-WORD     D!
  ' LCD-CURSOR-OFF CURSOR-OFF-WORD    D!
; INIT
