INCLUDE< device\m16def.f>

: TW_START			$08 ; INLINE-FOREVER
: TW_REP_START			$10 ; INLINE-FOREVER
: TW_MT_SLA_ACK			$18 ; INLINE-FOREVER
: TW_MT_SLA_NACK		$20 ; INLINE-FOREVER
: TW_MT_DATA_ACK		$28 ; INLINE-FOREVER
: TW_MT_DATA_NACK		$30 ; INLINE-FOREVER
: TW_MT_ARB_LOST		$38 ; INLINE-FOREVER
: TW_MR_ARB_LOST		$38 ; INLINE-FOREVER
: TW_MR_SLA_ACK			$40 ; INLINE-FOREVER
: TW_MR_SLA_NACK		$48 ; INLINE-FOREVER
: TW_MR_DATA_ACK		$50 ; INLINE-FOREVER
: TW_MR_DATA_NACK		$58 ; INLINE-FOREVER
: TW_ST_SLA_ACK			$A8 ; INLINE-FOREVER
: TW_ST_ARB_LOST_SLA_ACK	$B0 ; INLINE-FOREVER
: TW_ST_DATA_ACK		$B8 ; INLINE-FOREVER
: TW_ST_DATA_NACK		$C0 ; INLINE-FOREVER
: TW_ST_LAST_DATA		$C8 ; INLINE-FOREVER
: TW_SR_SLA_ACK			$60 ; INLINE-FOREVER
: TW_SR_ARB_LOST_SLA_ACK	$68 ; INLINE-FOREVER
: TW_SR_GCALL_ACK		$70 ; INLINE-FOREVER
: TW_SR_ARB_LOST_GCALL_ACK	$78 ; INLINE-FOREVER
: TW_SR_DATA_ACK		$80 ; INLINE-FOREVER
: TW_SR_DATA_NACK		$88 ; INLINE-FOREVER
: TW_SR_GCALL_DATA_ACK		$90 ; INLINE-FOREVER
: TW_SR_GCALL_DATA_NACK		$98 ; INLINE-FOREVER
: TW_SR_STOP			$A0 ; INLINE-FOREVER
: TW_NO_INFO			$F8 ; INLINE-FOREVER
: TW_BUS_ERROR			$00 ; INLINE-FOREVER
: TW_STATUS_MASK		1 TWS7 << 1 TWS6 << 1 TWS5 << 1 TWS4 << 1 TWS3 <<
				OR OR OR OR ; INLINE
: TW_STATUS@			TWSR IN TW_STATUS_MASK AND ; INLINE
: TW_READ			1 ; INLINE-FOREVER
: TW_WRITE			0 ; INLINE-FOREVER
