INCLUDE< device\m16def.f>	( Device definition file		)
INCLUDE< inits.f>		( System initialization			)
INCLUDE< temps.f>		( Works with temporary registers	)
INCLUDE< branch-loops.f>	( Helpers for loops/branch		)
INCLUDE< stack.f>		( Stack manipulation words		)
INCLUDE< logic.f>		( Bit logic				)
INCLUDE< compare.f>		( Compare words				)
INCLUDE< arithm.f>		( 8-bit arithmetics			)
INCLUDE< darithm.f>		( 16-bit arithmetics			)
INCLUDE< qarithm.f>		( 32-bit arithmetics			)
INCLUDE< convert.f>		( 8-16-32 conversion words		)
INCLUDE< interrupt.f>		( Interrupt control words		)
INCLUDE< memory.f>		( Memory manipulation words		)
INCLUDE< inout.f>		( Ports input/output words		)
INCLUDE< bits.f>		( Bit manipulation words		)
INCLUDE< other.f>		( Other words				)
( INCLUDE< allocate.f>		( Memory allocation			)
( INCLUDE< locals.f>		( Local variables			)
( INCLUDE< format.f>		( Numeric format words			)
( INCLUDE< cinout.f>		( Standard character input/output words	)
